import StoryblokProvider from '@/components/StoryblokProvider';
import { apiPlugin, storyblokInit } from '@storyblok/react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //  initialize StoryBlok on the server side
  storyblokInit({
    accessToken: process.env.SB_PREVIEW_TOKEN!!,
    use: [apiPlugin],
    apiOptions: {
      region: 'eu',
    },
    components: {},
  });
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </StoryblokProvider>
  );
}
